import React from 'react';
import { Gauge, Package, Sparkles, TrendingUp } from 'lucide-react';
import { categoryData, trendData } from '../data/mockData';
import DemandChart from '../components/charts/DemandChart';
import CategoryChart from '../components/charts/CategoryChart';
import ProductTable from '../components/common/ProductTable';
import StatCard from '../components/common/StatCard';
export default function Dashboard({ products, filtered, search, setSearch, onAdd, onExport, onImport, onNavigate }) {
 return <><div className="hero"><div><div className="eyebrow"><span />AI-POWERED RETAIL INTELLIGENCE</div><h1>Know what customers<br /><span>will want next.</span></h1><p>Turn social media signals and sales history into smarter demand forecasts.</p></div><div className="admin-actions"><button className="secondary-btn" onClick={onExport}>⇩ Export CSV</button><label className="secondary-btn import-btn">⇧ Import CSV<input type="file" accept=".csv,text/csv" onChange={onImport} /></label><button className="primary-btn" onClick={onAdd}>＋ Add Product</button></div></div><div className="stats-grid"><StatCard icon={Package} title="Products tracked" value={products.length} change="+12.4% this month" tone="purple" /><StatCard icon={TrendingUp} title="Trending products" value="18" change="+24.8% this week" tone="blue" /><StatCard icon={Sparkles} title="Predictions generated" value="1,284" change="+18.2% this month" tone="orange" /><StatCard icon={Gauge} title="Model confidence" value="91.6%" change="+3.7% this week" tone="green" /></div><div className="grid-two"><section className="panel chart-panel"><div className="panel-head"><div><h2>Demand momentum</h2><p>Predicted demand vs. social mentions</p></div></div><DemandChart data={trendData} /></section><section className="panel"><div className="panel-head"><div><h2>AI demand insight</h2><p>Latest model explanation</p></div><div className="ai-badge"><Sparkles size={14} /> AI</div></div><div className="prediction-box"><span>Wireless Earbuds</span><small>Next 7 days</small><strong>1,150 <small>units</small></strong><div className="confidence"><span>91% confidence</span><div><i style={{ width: '91%' }} /></div></div></div><div className="reason"><div className="reason-icon"><TrendingUp size={18} /></div><div><b>Demand is rising</b><p>Positive sentiment and social mentions are both accelerating.</p></div></div><button className="secondary-btn" onClick={() => onNavigate('Predictions')}>View full prediction</button></section></div><section className="panel products-panel"><div className="panel-head"><div><h2>Product portfolio</h2><p>Connected to your Spring Boot backend</p></div><div className="search">⌕<input placeholder="Search products..." value={search} onChange={event => setSearch(event.target.value)} /></div></div><ProductTable products={filtered} /></section><section className="panel category-panel"><div className="panel-head"><div><h2>Category demand</h2><p>Current trend strength</p></div></div><CategoryChart data={categoryData} /></section></>;
}
